### ISSUE TITLE
Investigate Memory Usage

### ISSUE THREAD

**Issue by jamesward** [webjars/webjars-file-service#1]
With `-Xmx256m` the app is using > 512m.

**Comment by mkurz** [comment]
@jamesward Is this project even in use?

**Comment by jamesward** [comment]
Yup! It powers all WebJars file stuff (num files, list files, etc) on https://www.webjars.org/

Regarding this issue, it's running on Heroku with a memory cap of 512MB of RAM.  Looks like it tops out on 410MB under normal usage. Using these JVM params:
```
-Xms128m -Xmx512m -XX:+UseCompressedOops -Xss512k -XX:MaxDirectMemorySize=64m
```

I don't think there is an issue with this any longer.  So closing.
