### ISSUE TITLE
Investigate Possible Race Condition

### ISSUE THREAD

**Issue by jamesward** [webjars/webjars-file-service#2]
Probably need some tests to validate what happens with multiple concurrent requests.

**Comment by jamesward** [comment]
For reference: https://github.com/jsdelivr/jsdelivr/issues/18265

**Comment by tipsy** [comment]
Hi @jamesward, this happened again with `https://cdn.jsdelivr.net/webjars/org.webjars.npm/buefy/0.9.3/dist/buefy.min.js` at around 8:19PM, Nov 23rd, CEST. I don't have a more specific timestamp, someone just posted in our Slack showing how one of our projects were broken.

**Comment by jamesward** [comment]
Thanks! I'm looking into this further. There hasn't been any recent changes that'd cause this.  So likely some race condition or bug that has been around for a while.  Do you know how quickly the file resolved?  Also, there is an easy way with RequireJS and WebJars to fallback to the assets served from your web app.  That might provide a reliable workaround until I get to the bottom of this.

**Comment by jimaek** [comment]
Btw since jsDelivr caches everything the 404 errors should only happen on uncached files.

**Comment by jamesward** [comment]
The cache headers are supposed to enable basically forever caching. So I need to investigate that as well.

**Comment by tipsy** [comment]
> So likely some race condition or bug that has been around for a while. Do you know how quickly the file resolved? 

It's been going on for months, but seems it's been happening more frequently recently. It usually fixes itself within a minute or two.

> Also, there is an easy way with RequireJS and WebJars to fallback to the assets served from your web app.

Thanks, we're going to do that as a last resort if this hasn't been resolved when we go live. 

> The cache headers are supposed to enable basically forever caching.

Yeah, I was going to say. Every file is versioned, so they can be cached forever.

**Comment by MartinKolarik** [comment]
> The cache headers are supposed to enable basically forever caching. So I need to investigate that as well.

If you are sure it's safe to cache everything for longer, we can easily override your caching rules on our side. Right now the cache time is only 1 hour at the few URLs I checked.

**Comment by jamesward** [comment]
@MartinKolarik Yeah, after investigation my headers were the default (1 hour) which shouldn't have been the case.  I'm rolling out a fix to that now.  So no need to override on your side.

**Comment by jamesward** [comment]
@tipsy There was a race condition with multiple requests for the same webjar. I've fixed that (and added a test for it). So hopefully this is more stable now.  Sorry for the issues!

**Comment by tipsy** [comment]
Thank you for the quick fix! 🎉
